### ISSUE TITLE
DRY with components/partials/tailwind classes

### ISSUE THREAD

**Issue by mhluska** [WebPraktikos/universal-resume#13]
There seems to be a lot of repetition in the html with classes being repeated. For example I see this a lot throughout the document:

```
<span class="absolute -ml-3 sm:-ml-3.2 select-none transform -translate-y-px">›</span>
```

Would it make sense to DRY this up somehow? Some ideas in order of difficulty:

1. Tailwind component classes: https://tailwindcss.com/docs/extracting-components
2. Use a template system like handlebars to add partials
3. Use Vue/React components

**Comment by WebPraktikos** [comment]
Hi there! 

That change would add more layers without adding benefits. This is the utility-first (functional) CSS approach — no naming things, no context switching, directly recognizing code, etc.

I use Ctrl+Shift+L in VS Code to select all occurrences of the selected classes.

**Comment by mhluska** [comment]
There's no benefit to DRY? Even your "utility-first" CSS library recommends it:

> Keeping a long list of utility classes in sync across many component instances can quickly become a real maintenance burden, so when you start running into painful duplication like this, it's a good idea to extract a component.

> For small components like buttons and form elements, creating a template partial or JavaScript component can often feel too heavy compared to a simple CSS class. In these situations, you can use Tailwind's @apply directive to easily extract common utility patterns to CSS component classes.

**Comment by WebPraktikos** [comment]
Of course it can be useful — for larger projects, with multiple files. Here, with one relatively small file, it’s not a maintenance issue.
