### ISSUE TITLE
Typography not the same on github pages vs served locally

### ISSUE THREAD

**Issue by ParvaizMansoori** [WebPraktikos/universal-resume#18]
When running npm serve locally, the typography is working properly. But when serving to github pages the typography is slightly different. 
![Incorrect typography](https://user-images.githubusercontent.com/97036546/175766242-c155a737-e113-4660-997d-c1813ebde3ab.png)
![correct typography](https://user-images.githubusercontent.com/97036546/175766244-dad28a75-9777-47e6-abe5-13b73ec28669.png)

**Comment by ParvaizMansoori** [comment]
any help? have spent hours trying to get this to work but I'm not able to figure out the issue

when i try git add styles.css things don't really seem to be working

**Comment by WebPraktikos** [comment]
Hi there. Is the issue solved?

**Comment by ParvaizMansoori** [comment]
> 

Hey, I investigated further and it was an issue of where the fonts were being looked for. Rather than the subrepository from where I activated the github page, it was looking for the fonts from my main github repository. I fixed by adding the fonts folder to my main repository. 

The issue might be a github page thing
