### ISSUE TITLE
Links aren't preserved when converting to PDF in Chrome

### ISSUE THREAD

**Issue by ReganBell** [WebPraktikos/universal-resume#19]
Anybody know a good workaround? Is this expected behavior?

**Comment by WebPraktikos** [comment]
Hi there. I've just tested it (Print > Destination: Save as PDF) and the links work fine after I open the PDF file.

**Comment by ReganBell** [comment]
Ah, thank you! I was saving as PDF from the system dialog. Didn't realize the functionality is different.
