### ISSUE TITLE
No padding-top on second page when printing multiple pages variant 

### ISSUE THREAD

**Issue by kopparam** [WebPraktikos/universal-resume#20]
When I try to print the multiple pages variant, the second and third page do not have any margin or padding on top of the page.
![image](https://user-images.githubusercontent.com/6135581/212519897-17233791-e624-4bab-8a5d-9e305bf9e6d9.png)

**Comment by WebPraktikos** [comment]
Thanks for reporting it. I’m working on fixing it. It is caused by a new Chrome version.

**Comment by WebPraktikos** [comment]
Adding `print:mt-16` on each page except the first one is the fix for now.
