### ISSUE TITLE
Top-margin on first section

### ISSUE THREAD

**Issue by mediabuff** [WebPraktikos/universal-resume#21]
Hi,
I am trying to replicate exactly what you have online (Letter size). My rendition adds top margin to the first 'section' - where as the online version does not. Please see the screen shots below.

<img width="427" alt="image" src="https://github.com/WebPraktikos/universal-resume/assets/5080114/0a2e8d58-2676-4a1d-b007-706a539f55d1">

<img width="385" alt="image" src="https://github.com/WebPraktikos/universal-resume/assets/5080114/57108e1b-c15a-4b16-bbaa-4bf9145e491e">

I have Tracked down to mt-8 

Defined as follows in your build.css

<img width="248" alt="image" src="https://github.com/WebPraktikos/universal-resume/assets/5080114/457f304c-ffc3-4432-b706-70634f53ec07">

.first\:mt-0:first-child {
    margin-top: 0
}

But I don't see where you override in your code base. Where is this coming from ?

**Comment by WebPraktikos** [comment]
Hi there! I'm sorry for not getting back to you sooner. I have just cloned the repo and run serve. On my side, the page (letter size) is the same as the demo page. I can't reproduce the issue.
