### ISSUE TITLE
Printing in Safari

### ISSUE THREAD

**Issue by ashtonmeuser** [WebPraktikos/universal-resume#4]
Printing in Safari (v12.1.2) causes issues with formatting. Layout looks fine prior to printing. Confirmed in v1.1.4 with all four demo pages. Printing did not adversely affect layout when using Chrome. See attached screenshot (letter) and document (multi-page).

![Screen Shot](https://user-images.githubusercontent.com/7253863/65101773-f79e5900-d97d-11e9-9415-cce3fb5b6f89.png)

[Marko Marković — Resume.pdf](https://github.com/WebPraktikos/universal-resume/files/3624095/Marko.Markovic.Resume.pdf)

**Comment by WebPraktikos** [comment]
Thanks for reporting. I didn’t do testing in Safari. One of the bugs, or the only bug, is probably ”Safari does not support multicolumn printing.” The same bug was fixed in Chrome at the end of 2015. Printing will not be supported in Safari, for now :/
