### ISSUE TITLE
Update filesystem for plug-and-play integration with GitHub pages

### ISSUE THREAD

**Issue by Cal-Hagner** [WebPraktikos/universal-resume#5]
Update the filesystem in order to play nicely with GitHub pages. Something like netlify is an additional something to do, and is more complicated than needed to host a nice static site CV without backend. Additionally, lack of a custom domain name will now result in nicer names than the defaults from netlify.

**Comment by WebPraktikos** [comment]
Merged. Thanks for the improvement. Very useful. :+1:
