### ISSUE TITLE
CSS not working

### ISSUE THREAD

**Issue by kunalbotla** [WebPraktikos/universal-resume#7]
The CSS formatting does not seem to be working when it is deployed to GitHub pages. When opening the HTML file on my computer or using the serve function the CSS seems to be working as expected

Attached is a screenshot:
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/25641153/73990151-49885100-4916-11ea-894b-075c0ce58d3d.png">

**Comment by WebPraktikos** [comment]
Hi there. Thanks for bringing this to my attention. I didn’t test nor document how to do it correctly. Now, it’s corrected.

Here’s the relevant part from the documentation:
“with additionally running git add docs/styles.css -f and committing changes, it’s ready for push to GitHub and integration with GitHub Pages. It may take some time for changes to occur. GitHub Pages are set by configuring Settings → Options → GitHub Pages → Source → /docs (free for public repos)“

**Comment by kunalbotla** [comment]
It’s not that it’s that the styles.css file is in the git ignore

**Comment by WebPraktikos** [comment]
Yep, that’s why you force push it with `git add docs/styles.css -f`. For further development, there’s no need for tracking of build code.

**Comment by kunalbotla** [comment]
Why not just remove it from the git ignore?

**Comment by WebPraktikos** [comment]
I only want to track source code, not generated code. Otherwise, one loses the purpose of using a source control system. In this case, sources are `tailwind.css` and `tailwind.config.js`.

**Comment by kunalbotla** [comment]
Ah ok, maybe just put this in the readme

**Comment by WebPraktikos** [comment]
I wrote it in the readme when I resolved the issue. (Check my first response.)
