### ISSUE TITLE
Contact info is positioned in a third column in Firefox

### ISSUE THREAD

**Issue by nfriend** [WebPraktikos/universal-resume#8]
In Firefox, the **Contact** section is rendered in a third column:

![Screen Shot 2020-02-25 at 10 43 05 AM](https://user-images.githubusercontent.com/1638631/75263266-bc6d4500-57bb-11ea-9238-4f43ce682d4c.png)

In Chrome, this section is (correctly) rendered in the bottom of the second column:

<img width="957" alt="Screen Shot 2020-02-25 at 10 44 22 AM" src="https://user-images.githubusercontent.com/1638631/75263359-de66c780-57bb-11ea-9096-c71910d5a22b.png">

**Comment by WebPraktikos** [comment]
Hey, thanks for letting me know! I’ll fix it soon.

**Comment by WebPraktikos** [comment]
It’s good now

**Comment by nfriend** [comment]
Amazing, thanks @WebPraktikos! 🚀
